local addonName, addonTable = ...

addonTable.Socials = { 
    {name="YouTube", url="https://www.youtube.com/oakensoul"}, 
    {name="Discord", url="https://discord.gg/FRGUFaEEVd"}, 
    {name="Twitch", url="https://www.twitch.tv/oakensoul"}, 
    {name="Patreon", url="https://www.patreon.com/Oakensoul"}, 
    {name="Ko-Fi", url="https://ko-fi.com/oakensoul"} 
}

addonTable.Patreons = {
    "Mandos",
    "Thomas Valhøj",
    "psykotedy",
    "Brian Ehlers",
    "mglass",
    "Vincent Murcia",
    "Shawn Snyder",
    "Emil Sundström",
    "Tony",
    "Mills Guild",
    "Tony",
    "Inuyasha",
    "Emmanuel leroy",
    "Casey",
    "Mike Ham",
    "Mike Saul",
    "Rob Richardson",
    "Michael Irving",
    "bcvbcfb",
    "Zacharias Kouvaras",
    "Topcat357",
    "Deckert Skilso",
    "Noël Léon Dalstein",
    "Romain Herlinvaux",
    "Omar Elsotouhy",
    "Daniel Girgsdies",
    "Paul Westervelt",
    "Typical Panda",
    "Jermaine Adams",
    "Justin Vaughn",
    "Allan Nielsen",
    "Naomi McMillan",
    "Mike Ham",
    "Thomas Nguyen",
    "sondel robi",
    "jonathan wester",
    "chris hellmuth",
    "Jon Jordan",
    "michael arguedas",
    "Devron Lee",
    "Michael j",
}
