local addonName, addonTable = ...

addonTable.Socials = { 
    {name="YouTube", url="https://www.youtube.com/oakensoul"}, 
    {name="Discord", url="https://discord.gg/FRGUFaEEVd"}, 
    {name="Twitch", url="https://www.twitch.tv/oakensoul"}, 
    {name="Patreon", url="https://www.patreon.com/Oakensoul"}, 
    {name="Ko-Fi", url="https://ko-fi.com/oakensoul"} 
}

addonTable.SpecialThanks = {
    { textKey = "Lowpitch on Discord - Korean localization and help with missing localization." },
}

addonTable.Patreons = {
    "Thomas Valhøj",
    "psykotedy",
    "Brian Ehlers",
    "mglass",
    "Vincent Murcia",
    "Shawn Snyder",
    "Emil Sundström",
    "Tony",
    "Inuyasha",
    "Emmanuel leroy",
    "Casey",
    "Mandos",
    "Rob Richardson",
    "Michael Irving",
    "Zacharias Kouvaras",
    "Topcat357",
    "Deckert Skilso",
    "Noël Léon Dalstein",
    "Romain Herlinvaux",
    "Daniel Girgsdies",
    "Paul Westervelt",
    "Typical Panda",
    "Jermaine Adams",
    "Justin Vaughn",
    "Allan Nielsen",
    "Jon Jordan",
    "michael arguedas",
    "Devron Lee",
    "Tenelle Mallard",
    "coot",
    "Michael J",
    "Edwin Cridland",
    "Robert D Jones",
    "stephiemarie78",
    "Edrick Nickerson",
    "B 87",
    "Nalu Rider",
    "Mark Hart",
    "Khalifa Almajid",
    "Scott Mortell",
    "Donald Ross",
    "Peter O'Toole",
    "George E",
    "Sparrowhawk Sr",
    "Chris Garland",
    "Josh Cooper",
    "Chris Nelms",
    "Bryan Erickson",
    "Chris Kerrigan",
    "Norving Gutierrez",
    "The Jason",
    "Symisch",
    "Alexander Hartwich",
    "Antonio Saez",
    "Blake Stover",
    "Jason Samalot",
    "Komosky",
    "Loonie74",
    "Randall Crank",
    "Harry Paap",
    "PhoenixLD",
    "Paul T",
    "Alexey Fedorov",
    "Roland",
    "Sridhar Mantha",
    "Bryan",
    "达永 叶",
    "Strike",
    "martin frimand",
    "JON",
    "von Minden Niklas",
    "Wall Martz",
    "thanosbel",
    "Benjamin Keene",
    "Ryan Couture",
    "Renegades Guild",
    "Marcel Dekker",
    "Christopher Saffle",
    "dwayne baldock",
    "MadCow",
}
