local addonName, addonTable = ...

addonTable.Socials = { 
    {name="YouTube", url="https://www.youtube.com/oakensoul"}, 
    {name="Discord", url="https://discord.gg/FRGUFaEEVd"}, 
    {name="Twitch", url="https://www.twitch.tv/oakensoul"}, 
    {name="Patreon", url="https://www.patreon.com/Oakensoul"}, 
    {name="Ko-Fi", url="https://ko-fi.com/oakensoul"} 
}

addonTable.SpecialThanks = {
    { textKey = "Lowpitch on Discord - Korean localization and help with missing localization." },
}

addonTable.Patreons = {
    "psykotedy",
    "Brian Ehlers",
    "mglass",
    "Shawn Snyder",
    "Emil Sundström",
    "Tony",
    "Inuyasha",
    "Emmanuel leroy",
    "Casey",
    "Rob Richardson",
    "Zacharias Kouvaras",
    "Topcat357",
    "Deckert Skilso",
    "Noël Léon Dalstein",
    "Romain Herlinvaux",
    "Daniel Girgsdies",
    "Paul Westervelt",
    "Typical Panda",
    "Jermaine Adams",
    "Justin Vaughn",
    "Allan Nielsen",
    "Doc_waffle",
    "Jon Jordan",
    "michael arguedas",
    "Devron Lee",
    "Tenelle Mallard",
    "Iury Sampaio",
    "coot",
    "Edwin Cridland",
    "Robert D Jones",
    "Edrick Nickerson",
    "B 87",
    "Nalu Rider",
    "Mark Hart",
    "Khalifa Almajid",
    "Andrew Steltz",
    "Scott Mortell",
    "Donald Ross",
    "Peter O'Toole",
    "George E",
    "Sparrowhawk Sr",
    "Chris Garland",
    "Josh Cooper",
    "Chris Nelms",
    "Bryan Erickson",
    "Chris Kerrigan",
    "Norving Gutierrez",
    "The Jason",
    "Symisch",
    "Alexander Hartwich",
    "Antonio Saez",
    "Frank franz",
    "Blake Stover",
    "Loonie74",
    "PhoenixLD",
    "Paul T",
    "Alexey Fedorov",
    "Roland",
    "Sridhar Mantha",
    "Bryan",
    "Strike",
    "martin frimand",
    "JON",
    "Wall Martz",
    "Benjamin Keene",
    "Ryan Couture",
    "Renegades Guild",
    "Marcel Dekker",
    "Christopher Saffle",
    "dwayne baldock",
    "MadCow",
    "Rooobn1781",
    "Brian Wease",
    "lloyd spencer",
    "Sumith Imtiaz",
    "Grotesk",
    "Alex Tegnazian",
    "Laurie Timothy",
    "evans starzinger",
    "JimmyJam",
    "Mack",
    "Jennifer Carlson",
    "Gianluca Berian",
}
